# Generated by Django 4.2.4 on 2023-08-09 10:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_rename_articlenews_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='user_views',
            field=models.ManyToManyField(blank=True, related_name='new_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
