# Generated by Django 4.2.2 on 2023-07-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0006_resume'),
        ('core', '0003_vacancy_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='resume',
            field=models.ManyToManyField(to='worker.resume'),
        ),
    ]
