# Generated by Django 4.2.2 on 2023-07-11 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0006_resume'),
        ('core', '0004_vacancy_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.resume')),
                ('vacancy', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.vacancy')),
            ],
        ),
    ]
