# Generated by Django 4.2.2 on 2023-07-11 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_category_resume_remove_category_vacancy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='kategoriya'),
        ),
    ]
