# Generated by Django 4.2.2 on 2023-07-11 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_vacancy_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='категория'),
        ),
    ]
