# Generated by Django 4.2.2 on 2023-07-11 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_vacancy_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='resume',
        ),
    ]
