# Generated by Django 4.2.2 on 2023-07-20 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_vacancy_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
