# Generated by Django 4.2.2 on 2023-07-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0006_resume'),
        ('core', '0011_delete_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_date', models.DateField()),
                ('workers', models.ManyToManyField(blank=True, related_name='company', to='worker.worker')),
            ],
        ),
    ]
