# Generated by Django 4.2.2 on 2023-07-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_comment_alter_worker_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
