# Generated by Django 4.2.2 on 2023-07-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0006_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo/', verbose_name='Candidate Picture'),
        ),
    ]
